# general settings
name: PlainUSR_general_x4_gt256_DIV2K_LSDIR_500k_B64G1_wandb
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DIV2K_LSDIR_train_sub
    type: PairedImageDataset
    dataroot_gt: [datasets/DIV2K/DIV2K_train_HR_sub, datasets/LSDIR/HR/train_sub]
    dataroot_lq: [datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub, datasets/LSDIR/X4/train_sub]
    # (for lmdb)d
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: DIV2K_LSDIR_valid
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K_LSDIR_valid/DIV2K_LSDIR_valid_HR
    dataroot_lq: datasets/DIV2K_LSDIR_valid/DIV2K_LSDIR_valid_LR
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

# network structures
network_g:
  type: PlainUSR_general
  n_feat: 48
  im_feat: [48,32,16]
  attn_feat: 8
  scale: 4


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000,400000,450000,475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: false
    ssim: 
      type: calculate_ssim
      crop_border: 2
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: NTIRE2025 ESR
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
